/**
 * Native Anwendungsentwicklung mit SAP HANA
 *
 * Prädikative Analysen
 *
 * $Autor: Stefan Kühnlein, Holger Seubert
 * $Version: 1.0
*/

// Führen Sie den Befehl in der SQL Konsole aus.

CREATE COLUMN TABLE PAL_MULTIVARSTAT_DATA_TBL LIKE
PAL_MULTIVARSTAT_DATA_T;
INSERT INTO PAL_MULTIVARSTAT_DATA_TBL VALUES (1,2.4);
INSERT INTO PAL_MULTIVARSTAT_DATA_TBL VALUES (5,3.5);
INSERT INTO PAL_MULTIVARSTAT_DATA_TBL VALUES (3,8.9);
INSERT INTO PAL_MULTIVARSTAT_DATA_TBL VALUES (10,-1.4);
INSERT INTO PAL_MULTIVARSTAT_DATA_TBL VALUES (-4,-3.5);
INSERT INTO PAL_MULTIVARSTAT_DATA_TBL VALUES (11,32.8);